github.com:
    users:
        a-cream:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: a-cream
