github.com:
    users:
        a-cream:
            oauth_token: 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
    git_protocol: ssh
    user: a-cream
    oauth_token: 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
