"ui.background" = { bg = "#1C1917" }
"ui.text" = { fg = "#B4BDC3" }
"ui.selection" = { bg = "#3D4042" }
"ui.linenr" = { fg = "#685F5A" }
"ui.linenr.selected" = { fg = "#B4BDC3", modifiers = ["bold"] }
"ui.statusline" = { fg = "#B4BDC3", bg = "#352F2D" }
"ui.statusline.inactive" = { fg = "#CAD0D4", bg = "#272321" }
"ui.cursor" = { fg = "#1C1917", bg = "#C4CACF" }
"ui.cursor.primary" = { fg = "#1C1917", bg = "#797F84" }
"ui.menu.selected" = { fg = "#B4BDC3", modifiers = ["bold"] }

"comment" = { fg = "#6e6763", modifiers = ["italic"] }
"constant" = { fg = "#979fa4" }
"function" = { fg = "#b4bdc3" }
"keyword" = { fg = "#b4bdc3", modifiers = ["bold"] }
"operator" = { fg = "#b4bdc3", modifiers = ["bold"] }
"string" = { fg = "#979fa4" }
"type" = { fg = "#a1938c" }
"variable" = { fg = "#979fa4" }
"tag" = { fg = "#8d9499" }
"attribute" = { fg = "#b4bdc3", modifiers = ["bold"] }
"namespace" = { fg = "#868c91" }
"special" = { fg = "#8d9499", modifiers = ["bold"] }
"label" = { fg = "#b4bdc3", modifiers = ["bold"] }
"punctuation" = { fg = "#867a74" }
"markup" = { fg = "#8d9499" }
"diff" = { fg = "#80c080" }

"comment.line" = { fg = "#6e6763", modifiers = ["italic"] }
"comment.block" = { fg = "#6e6763", modifiers = ["italic"] }
"comment.block.documentation" = { fg = "#6e6763", modifiers = ["italic"] }

"constant.builtin" = { fg = "#868c91", modifiers = ["italic"] }
"constant.builtin.boolean" = { fg = "#868c91", modifiers = ["italic"] }
"constant.builtin.character" = { fg = "#868c91", modifiers = ["italic"] }
"constant.builtin.numeric" = { fg = "#868c91", modifiers = ["italic"] }
"constant.builtin.numeric.integer" = { fg = "#868c91", modifiers = ["italic"] }
"constant.builtin.numeric.float" = { fg = "#868c91", modifiers = ["italic"] }

"function.builtin" = { fg = "#8d9499", modifiers = ["bold"] }
"function.method" = { fg = "#b4bdc3" }
"function.method.private" = { fg = "#b4bdc3" }
"function.macro" = { fg = "#b4bdc3", modifiers = ["bold"] }
"function.special" = { fg = "#8d9499", modifiers = ["bold"] }

"keyword.control" = { fg = "#b4bdc3", modifiers = ["bold"] }
"keyword.control.conditional" = { fg = "#b4bdc3", modifiers = ["bold"] }
"keyword.control.repeat" = { fg = "#b4bdc3", modifiers = ["bold"] }
"keyword.control.import" = { fg = "#b4bdc3", modifiers = ["bold"] }
"keyword.control.return" = { fg = "#b4bdc3", modifiers = ["bold"] }
"keyword.control.exception" = { fg = "#b4bdc3", modifiers = ["bold"] }
"keyword.operator" = { fg = "#b4bdc3", modifiers = ["bold"] }
"keyword.directive" = { fg = "#b4bdc3", modifiers = ["bold"] }
"keyword.function" = { fg = "#b4bdc3", modifiers = ["bold"] }
"keyword.storage" = { fg = "#a1938c" }
"keyword.storage.type" = { fg = "#a1938c" }
"keyword.storage.modifier" = { fg = "#a1938c" }

"string.regexp" = { fg = "#868c91", modifiers = ["italic"] }
"string.special" = { fg = "#8d9499", modifiers = ["bold"] }
"string.special.path" = { fg = "#8d9499", modifiers = ["bold"] }
"string.special.url" = { fg = "#8d9499", modifiers = ["bold"] }
"string.special.symbol" = { fg = "#979fa4" }

"type.builtin" = { fg = "#a1938c" }
"type.parameter" = { fg = "#a1938c" }
"type.enum" = { fg = "#a1938c" }
"type.enum.variant" = { fg = "#a1938c" }
"type.constructor" = { fg = "#a1938c" }

"variable.builtin" = { fg = "#868c91", modifiers = ["italic"] }
"variable.parameter" = { fg = "#979fa4" }
"variable.member" = { fg = "#979fa4" }
"variable.member.private" = { fg = "#979fa4" }

"punctuation.delimiter" = { fg = "#867a74" }
"punctuation.bracket" = { fg = "#867a74" }
"punctuation.special" = { fg = "#867a74" }

"markup.heading" = { fg = "#b4bdc3", modifiers = ["bold"] }
"markup.heading.marker" = { fg = "#b4bdc3" }
"markup.heading.1" = { fg = "#b4bdc3" }
"markup.heading.2" = { fg = "#b4bdc3" }
"markup.heading.3" = { fg = "#b4bdc3" }
"markup.heading.4" = { fg = "#b4bdc3" }
"markup.heading.5" = { fg = "#b4bdc3" }
"markup.heading.6" = { fg = "#b4bdc3" }
"markup.list" = { fg = "#8d9499" }
"markup.list.unnumbered" = { fg = "#8d9499" }
"markup.list.numbered" = { fg = "#8d9499" }
"markup.list.checked" = { fg = "#8d9499" }
"markup.list.unchecked" = { fg = "#8d9499" }
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["strikethrough"] }
"markup.link" = { fg = "#868c91" }
"markup.link.url" = { fg = "#868c91" }
"markup.link.label" = { fg = "#8d9499" }
"markup.link.text" = { fg = "#979fa4" }
"markup.quote" = { fg = "#979fa4" }
"markup.raw" = { fg = "#868c91" }
"markup.raw.inline" = { fg = "#868c91" }
"markup.raw.block" = { fg = "#868c91" }

"diff.plus" = { fg = "#80c080" }
"diff.plus.gutter" = { fg = "#80c080" }
"diff.minus" = { fg = "#ff6c6c" }
"diff.minus.gutter" = { fg = "#ff6c6c" }
"diff.delta" = { fg = "#ffbf00" }
"diff.delta.moved" = { fg = "#ffbf00" }
"diff.delta.conflict" = { fg = "#ffbf00" }
"diff.delta.gutter" = { fg = "#ffbf00" }
